""""
This script creates three sets of data. One is a disk, the other is a square.
Each set of data is composed of 500 patterns. They are  generated by add noises to
the original pattern.
"""

import numpy as np
import h5py as h5

"""
Generate a h5 file to hold the data
"""

with h5.File('../../test/DiffusionMap/output/raw_1D.h5', 'w') as h5file:
    for r in range(20):
        """
        Generate patterns for square
        """

        pattern_num_1 = np.random.randint(low=5, high=100)

        original_square = np.zeros((128, 128))
        original_square[45:72, 45:72] = 40

        square_stack = np.zeros((pattern_num_1, 128, 128))
        for l in range(pattern_num_1):
            square_stack[l] = original_square + np.random.rand(128, 128) * 30

        """
        Generate patterns for circle
        """
        pattern_num_2 = np.random.randint(low=5, high=100)
        original_disk = np.zeros((128, 128))
        for l in range(128):
            for m in range(128):
                if (l - 63.5) ** 2 + (m - 63.5) ** 2 <= 400:
                    original_disk[l, m] = 68

        disk_stack = np.zeros((pattern_num_2, 128, 128))
        for l in range(pattern_num_2):
            disk_stack[l] = original_disk + np.random.rand(128, 128) * 30

        h5file.create_dataset(str(2 * r), data=np.reshape(square_stack, [pattern_num_1, 128 * 128]))
        h5file.create_dataset(str(2 * r + 1), data=np.reshape(disk_stack, [pattern_num_2, 128 * 128]))
