# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\layout.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1573, 775)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.splitter = QtWidgets.QSplitter(self.centralwidget)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.tabWidget = QtWidgets.QTabWidget(self.splitter)
        self.tabWidget.setMinimumSize(QtCore.QSize(100, 100))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(16)
        self.tabWidget.setFont(font)
        self.tabWidget.setObjectName("tabWidget")
        self.general = QtWidgets.QWidget()
        self.general.setObjectName("general")
        self.gridLayout = QtWidgets.QGridLayout(self.general)
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton_7 = QtWidgets.QPushButton(self.general)
        self.pushButton_7.setObjectName("pushButton_7")
        self.gridLayout.addWidget(self.pushButton_7, 4, 1, 1, 1)
        self.pushButton_9 = QtWidgets.QPushButton(self.general)
        self.pushButton_9.setObjectName("pushButton_9")
        self.gridLayout.addWidget(self.pushButton_9, 5, 0, 1, 1)
        self.pushButton_8 = QtWidgets.QPushButton(self.general)
        self.pushButton_8.setObjectName("pushButton_8")
        self.gridLayout.addWidget(self.pushButton_8, 7, 1, 1, 1)
        self.pushButton_10 = QtWidgets.QPushButton(self.general)
        self.pushButton_10.setObjectName("pushButton_10")
        self.gridLayout.addWidget(self.pushButton_10, 5, 2, 1, 1)
        self.pushButton_6 = QtWidgets.QPushButton(self.general)
        self.pushButton_6.setObjectName("pushButton_6")
        self.gridLayout.addWidget(self.pushButton_6, 11, 0, 1, 1)
        self.pushButton_13 = QtWidgets.QPushButton(self.general)
        self.pushButton_13.setObjectName("pushButton_13")
        self.gridLayout.addWidget(self.pushButton_13, 10, 0, 1, 1)
        self.pushButton_11 = QtWidgets.QPushButton(self.general)
        self.pushButton_11.setObjectName("pushButton_11")
        self.gridLayout.addWidget(self.pushButton_11, 10, 2, 1, 1)
        self.pushButton_12 = QtWidgets.QPushButton(self.general)
        self.pushButton_12.setObjectName("pushButton_12")
        self.gridLayout.addWidget(self.pushButton_12, 11, 2, 1, 1)
        self.pushButton_3 = QtWidgets.QPushButton(self.general)
        self.pushButton_3.setObjectName("pushButton_3")
        self.gridLayout.addWidget(self.pushButton_3, 0, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.general)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.general)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.general)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.gridLayout.addWidget(self.lineEdit_3, 2, 1, 1, 3)
        self.lineEdit = QtWidgets.QLineEdit(self.general)
        self.lineEdit.setMinimumSize(QtCore.QSize(0, 0))
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout.addWidget(self.lineEdit, 1, 1, 1, 3)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.general)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.gridLayout.addWidget(self.lineEdit_2, 0, 1, 1, 3)
        self.tabWidget.addTab(self.general, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.graphicsView_3 = QtWidgets.QGraphicsView(self.tab)
        self.graphicsView_3.setGeometry(QtCore.QRect(260, 30, 171, 151))
        self.graphicsView_3.setObjectName("graphicsView_3")
        self.graphicsView = QtWidgets.QGraphicsView(self.tab)
        self.graphicsView.setGeometry(QtCore.QRect(50, 30, 161, 151))
        self.graphicsView.setObjectName("graphicsView")
        self.graphicsView_5 = QtWidgets.QGraphicsView(self.tab)
        self.graphicsView_5.setGeometry(QtCore.QRect(50, 240, 161, 151))
        self.graphicsView_5.setObjectName("graphicsView_5")
        self.graphicsView_4 = QtWidgets.QGraphicsView(self.tab)
        self.graphicsView_4.setGeometry(QtCore.QRect(260, 240, 171, 151))
        self.graphicsView_4.setObjectName("graphicsView_4")
        self.tabWidget.addTab(self.tab, "")
        self.roi = QtWidgets.QWidget()
        self.roi.setObjectName("roi")
        self.pushButton = QtWidgets.QPushButton(self.roi)
        self.pushButton.setGeometry(QtCore.QRect(10, 410, 261, 41))
        self.pushButton.setObjectName("pushButton")
        self.label = QtWidgets.QLabel(self.roi)
        self.label.setGeometry(QtCore.QRect(10, 200, 351, 31))
        self.label.setObjectName("label")
        self.textBrowser = QtWidgets.QTextBrowser(self.roi)
        self.textBrowser.setGeometry(QtCore.QRect(10, 230, 301, 41))
        self.textBrowser.setObjectName("textBrowser")
        self.pushButton_2 = QtWidgets.QPushButton(self.roi)
        self.pushButton_2.setGeometry(QtCore.QRect(10, 360, 261, 41))
        self.pushButton_2.setObjectName("pushButton_2")
        self.tabWidget.addTab(self.roi, "")
        self.propogration = QtWidgets.QWidget()
        self.propogration.setObjectName("propogration")
        self.tabWidget.addTab(self.propogration, "")
        self.gridLayout_2.addWidget(self.splitter, 0, 1, 1, 1)
        self.graphicsView_2 = QtWidgets.QGraphicsView(self.centralwidget)
        self.graphicsView_2.setObjectName("graphicsView_2")
        self.gridLayout_2.addWidget(self.graphicsView_2, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1573, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.pushButton_3.clicked.connect(MainWindow.load_eigenvectors)
        self.pushButton_7.clicked.connect(MainWindow.move_upward)
        self.pushButton_10.clicked.connect(MainWindow.move_to_right)
        self.pushButton_8.clicked.connect(MainWindow.move_downward)
        self.pushButton_9.clicked.connect(MainWindow.move_to_left)
        self.pushButton_11.clicked.connect(MainWindow.zoom_in)
        self.pushButton_12.clicked.connect(MainWindow.zoom_out)
        self.pushButton_13.clicked.connect(MainWindow.reset_manifold)
        self.pushButton_6.clicked.connect(MainWindow.show_manifold)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_7.setText(_translate("MainWindow", "Up"))
        self.pushButton_9.setText(_translate("MainWindow", "Left"))
        self.pushButton_8.setText(_translate("MainWindow", "Down"))
        self.pushButton_10.setText(_translate("MainWindow", "Right"))
        self.pushButton_6.setText(_translate("MainWindow", "View"))
        self.pushButton_13.setText(_translate("MainWindow", "Reset"))
        self.pushButton_11.setText(_translate("MainWindow", "Zoom In"))
        self.pushButton_12.setText(_translate("MainWindow", "Zoom Out"))
        self.pushButton_3.setText(_translate("MainWindow", "Load "))
        self.label_2.setText(_translate("MainWindow", "X-axis"))
        self.label_3.setText(_translate("MainWindow", "Y-axis"))
        self.lineEdit_3.setText(_translate("MainWindow", "2"))
        self.lineEdit.setText(_translate("MainWindow", "1"))
        self.lineEdit_2.setText(_translate("MainWindow", "C:\\Users\\haoyu\\Documents\\Python Scripts\\diffusion_map_dev\\fake_eigens.npy"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.general), _translate("MainWindow", "General"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Inspect"))
        self.pushButton.setText(_translate("MainWindow", "Save Selected Region"))
        self.label.setText(_translate("MainWindow", "Number of Selected Samples"))
        self.pushButton_2.setText(_translate("MainWindow", "Select a Region"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.roi), _translate("MainWindow", "ROI"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.propogration), _translate("MainWindow", "Prop"))

